../icons/kiriki-16.xpm /usr/share/pixmaps
../icons/kiriki.xpm /usr/share/pixmaps
usr/games/kiriki
usr/share/applications/org.kde.kiriki.desktop
usr/share/doc/HTML/en/kiriki/
usr/share/icons/hicolor/128x128/apps/kiriki.png
usr/share/icons/hicolor/16x16/apps/kiriki.png
usr/share/icons/hicolor/22x22/apps/kiriki.png
usr/share/icons/hicolor/32x32/apps/kiriki.png
usr/share/icons/hicolor/48x48/apps/kiriki.png
usr/share/icons/hicolor/64x64/apps/kiriki.png
usr/share/kiriki/*
usr/share/kxmlgui5/kiriki/kirikiui.rc
